name: CA Certificate Sync

on:
  schedule:
    # 每年6月15日下午4:04运行
    # I AM THE STORM THAT IS APPROACHING
    - cron: '4 16 15 6 *'
  workflow_dispatch: 

permissions:
  contents: write
  packages: read

jobs:
  sync-certificates:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      
      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          sudo pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y ca-certificates libnss3-tools openssl cabextract wget
      
      - name: 同步证书
        run: |
          # 使用sudo执行脚本以获取root权限
          sudo python3 scripts/sync_certificates.py --clean | tee run.log
          # 获取证书数量
          CERT_COUNT=$(find certs -name "*.crt" | wc -l)
          echo "收集到 $CERT_COUNT 个证书"
          
          # 修复权限
          sudo chmod -R 755 certs
          sudo chmod 644 certs/*.crt
          sudo chmod 644 index.html
          
          # 复制assets到根目录
          mkdir -p assets
          cp -r templates/assets/* assets/
      
      - name: 提交证书更新
        run: |
          # 配置Git用户
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          # 设置SSH密钥
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          
          # 添加更改并提交
          git add -f certs/ index.html assets/
          
          # 获取当前日期
          DATE=$(date +"%Y-%m-%d")
          
          # 提交和推送
          git commit -m "更新CA证书库 ($DATE)" || echo "没有更改需要提交"
          
          # 使用SSH方式推送
          git remote set-url origin git@github.com:${GITHUB_REPOSITORY}.git
          git push origin HEAD:${GITHUB_REF}

      - name: 压缩日志文件
        if: always()
        run: |
          # 创建日志目录
          mkdir -p logs
          
          # 复制所有日志文件到logs目录
          find . -name "*.log" -exec cp {} logs/ \;
          find . -name "*log*" -type f -not -path "*/\.*" -not -path "*/logs/*" -exec cp {} logs/ \;
          
          # 压缩日志文件
          tar -czvf logs.tar.gz logs/
          
          echo "日志文件已压缩为 logs.tar.gz"

      - name: 上传日志文件
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: logs
          path: logs.tar.gz
          retention-days: 60
      
      - name: 创建新版本
        uses: softprops/action-gh-release@v1
        with:
          name: "CA证书库 ${{ github.event.repository.updated_at }}"
          tag_name: "release-${{ github.event.repository.updated_at }}"
          body: |
            CA证书自动更新，发布日期: ${{ github.event.repository.updated_at }}
            
            此版本包含从以下来源收集的最新CA根证书:
            - Ubuntu ca-certificates
            - Firefox的PEM证书链
            - Microsoft Windows证书更新
            - Python certifi库
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
